apiVersion: v1
kind: ReplicationController
metadata:
  name: myrcpod
spec:
    replicas: 5
    template:
      metadata:
         labels:
          app: test
      spec:
        containers:
         - image: nginx
           name: mycont
           ports:
             - containerPort: 80
           startupProbe:
              httpGet:
                 path: /index.html
                 port: 80
